name:                shorturi
version:             1.0.0
license:             MIT
author:              "Jappie Klooster"
maintainer:          "jappieklooster@hotmail.com"
copyright:           "2020 Jappie Klooster"
github:              "jappeace/shorturi"

extra-source-files:
- Readme.md
- LICENSE
- Changelog.md

ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -Wincomplete-record-updates
    - -Widentities
    - -Wcpp-undef
    - -fwarn-tabs
    - -Wpartial-fields

# from https://lexi-lambda.github.io/blog/2018/02/10/an-opinionated-guide-to-haskell-in-2018/
default-extensions:
  # trivial
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - InstanceSigs
  - MultiParamTypeClasses
  # only activated once used
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - TupleSections
  # no cost deriving power
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - StandaloneDeriving
  # used everywhere anyway
  - OverloadedStrings
  # ehh syntax
  - TypeApplications

dependencies:
- base >= 4.7 && < 5
- servant-server
- servant
- network-uri
- aeson
- mtl
- warp
- text
- persistent-sqlite
- persistent
- monad-logger
- base64 # oh a friend of mine maintains this.

library:
  source-dirs: src

executables:
  exe:
    main:                exe.hs
    source-dirs:         app
    dependencies:
    - shorturi
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  unit:
    main:                Spec.hs
    source-dirs:
    - test
    dependencies:
    - hspec
    - hspec-core
    - shorturi
    - QuickCheck
    - servant-quickcheck
    - quickcheck-instances
